# deploys changes to production when the application
# has been e2e-tested on the master branch
name: deploy
on:
  workflow_run: ["e2e"]
  types:
    - completed
  branches:
    - master
    
   
jobs:
  deploy:
    # only run if the e2e-test was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chat-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Deploy migrations
        run:
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
