name: e2e
on:
  push:
    branches:
      - master
   
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chat-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0
      - name: Start Supabase
        run: supabase start
        working-directory: ./
      - name: Install dependencies
        run: npm ci
      - name: Run migration
        run: npx prisma migrate dev
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
      - name: Run e2e tests
        run: npm run e2e
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
